"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
"""

def findTheDifference(s, t):
        from collections import Counter
        
        count_s = Counter(s)
        count_t = Counter(t)
        
        for char in count_t:
            if count_t[char] != count_s.get(char, 0):
                return char
